[build]
  command = "npm run build:va"
  publish = "va-site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/contact/"
  to = "/contact-us/"
  status = 301

[[redirects]]
  from = "/home/"
  to = "/"
  status = 301
